**Title:** LRR Case Study - Exploratory Analysis for Part 2<br>
**Created By:** Begimay Ahmatova<br>
**Created Date:** 2026-10-02<br>
**Description:** Deep dive into raw files for company crosswalk & entity resolution.<br>

In [1]:
## libraries
import duckdb as db
import pandas as pd

In [2]:
con = db.connect("lrr.duckdb", read_only=True)

In [3]:
company = con.sql("SELECT * FROM deduped_company").df()
company.head()

,id,normalized_name,informalname,cleaned_informalname,website,domain,normalized_phone,city,state,postalcode,country,foundingyear,companytype,parentid,parentcompany,totalamountinvested,nolongerinbusiness,modified_date
0,9700,Medi-Code,Medi-Code,medi-code,http://medi-code.com,medi-code.com,+18324372029,Katy,Texas,77494,United States,2009,1,<NA>,NaN,<NA>,False,2026-09-15
1,20074,Marketware,Marketware,marketware,https://marketware.com,marketware.com,+18019444230,Sandy,Utah,84094,United States,2014,4,1665037,Medsphere Systems Corporation,5900000,False,2026-07-16
2,28462,VCNetwork,VCNetwork,vcnetwork,https://vcnetwork.org,vcnetwork.org,,San Francisco,California,94114,United States,1997,5,<NA>,NaN,<NA>,False,2026-09-11
3,35837,Complipoint,Complipoint,complipoint,https://www.complipoint.com,complipoint.com,+18586732174,San Diego,California,92127,United States,2002,8,204227,Applications International Corp. (AIC),<NA>,False,2025-11-26
4,45311,FlexiInternational Software,FlexiInternational Software,flexiinternational software,https://www.flexi.com,flexi.com,+18003539492,Shelton,Connecticut,06484,United States,1992,3,<NA>,NaN,<NA>,False,2026-08-08

In [4]:
accounts = pd.read_csv("account.csv")
accounts.head()

,id,isdeleted,masterrecordid,name,type,recordtypeid,parentid,billingstreet,billingcity,billingstate,...,fintrx_x3_year_aum_growth__c,fintrx_x5_year_aum_growth__c,acquired_merged__c,keystone_recommended_lead_score__c,rls_delta__c,last_logged_activity__c,acquired_by_merged_with__c,company_source__c,source__c,estimated_arr__c
0,00157Q1WAHSCDPHCUN,False,NaN,"Rare Earth Exploration, LLC",NaN,NaN,NaN,NaN,Garland,Texas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,001R7G4RI0GA09H5ZJ,False,NaN,Kenton Grant Consulting,NaN,NaN,NaN,NaN,Tulsa,Oklahoma,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0012ABVJ564CCELZ4K,False,NaN,"GUTHY-RENKER, LLC",NaN,NaN,NaN,NaN,El Segundo,California,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,001R0ST0DTW00BXMZZ,False,NaN,SOS TRUCK SERVICE,NaN,NaN,NaN,NaN,Ontario,California,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,00186JM0HJK76GBGEK,False,NaN,Nutrition Partners Inc.,NaN,NaN,NaN,NaN,Airdrie,Alberta,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
## data types
pd.set_option("display.max_rows", None)
print(accounts.dtypes.to_string(), "\n")

## null / distinct profile for key columns
cols = ["id", "name", "billingcity", "billingstate", "billingcountry", "phone", "website", "domain__c"]
print("rows:", len(accounts))

profile = pd.DataFrame({
    "dtype": accounts[cols].dtypes.astype(str),
    "nulls": accounts[cols].isna().sum(),
    "null_pct": (accounts[cols].isna().mean() * 100).round(2),
    "distinct": accounts[cols].nunique(dropna=True),
})
profile["distinct_pct"] = (profile["distinct"] / (len(accounts) - profile["nulls"]) * 100).round(2)
profile

id                                               str
isdeleted                                       bool
masterrecordid                               float64
name                                             str
type                                         float64
recordtypeid                                 float64
parentid                                     float64
billingstreet                                float64
billingcity                                      str
billingstate                                     str
billingpostalcode                            float64
billingcountry                                   str
billinglatitude                              float64
billinglongitude                             float64
billinggeocodeaccuracy                       float64
billingaddress                               float64
shippingstreet                               float64
shippingcity                                 float64
shippingstate                                float64
shippingpostalcode                           float64
shippingcountry                              float64
shippinglatitude                             float64
shippinglongitude                            float64
shippinggeocodeaccuracy                      float64
shippingaddress                              float64
phone                                            str
website                                          str
photourl                                     float64
industry                                     float64
numberofemployees                            float64
ownership                                    float64
description                                  float64
ownerid                                      float64
createddate                                      str
createdbyid                                  float64
lastmodifieddate                             float64
lastmodifiedbyid                             float64
systemmodstamp                               float64
lastactivitydate                             float64
lastvieweddate                               float64
lastreferenceddate                           float64
jigsawcompanyid                              float64
sort_id                                      float64
fax                                          float64
accountnumber                                float64
sic                                          float64
annualrevenue                                float64
tickersymbol                                 float64
rating                                       float64
site                                         float64
jigsaw                                       float64
accountsource                                    str
sicdesc                                      float64
ispartner                                    float64
iscustomerportal                             float64
channelprogramname                           float64
channelprogramlevelname                      float64
deal_team__c                                 float64
mds__c                                       float64
year_of_financials__c                        float64
sub_sector__c                                float64
profession__c                                float64
lender_security_type__c                      float64
check_size_min__c                            float64
project__c                                   float64
company_power_of_1__c                        float64
ss_country__c                                float64
third_party_company_type__c                  float64
third_party_firm_specialization__c           float64
third_party_firm_expertise__c                float64
prefered_provider_status__c                  float64
third_party_typical_engagement_type__c       float64
sourcing_lead_name__c                        float64
total_third_party_spend__c                   float64
avg_value_of_engagement__c                   float64
third_party_network_tag__c                   float64
lp__c                                        float64
ss_3mo_growth_rate__c                        float64
quality_of_output_score__c                   float64
ss_6mo_growth_rate__c                        float64
likelihood_to_recommend_to_a_colleague__c    float64
engagement_price__c                          float64
third_party_projects_completed__c            float64
vct_owner__c                                 float64
of_primary_financials__c                     float64
lid__linkedin_company_id__c                  float64
check_size_max__c                            float64
estimated_of_employees__c                    float64
industry_overlap__c                          float64
sector__c                                    float64
avg__c                                       float64
estimated_revenue__c                         float64
domain__c                                        str
arr_multiple_range__c                        float64
pricing__c                                   float64
ebitda_min_max__c                            float64
estimated_percentage_of_growth__c            float64
estimated_ebitda__c                          float64
short_description__c                         float64
loan_to_value__c                             float64
debt_to_equity__c                            float64
okay_with_llr_as_minority__c                 float64
midlevels__c                                 float64
of_primary_opportunities__c                  float64
opportunity_stage__c                         float64
acct_count__c                                float64
number_of_qualify_verify_opps__c             float64
position_to_term_sheet_opp_count__c          float64
annual_sell_side__c                          float64
engagement_model__c                          float64
intermediary_marketing_tier__c               float64
relationship_status__c                       float64
relationship_status_color__c                 float64
relationship_commentary__c                   float64
average_diligence_price__c                   float64
ss_9mo_growth_rate__c                        float64
ss_12mo_growth_rate__c                       float64
of_estimate_financials__c                    float64
primary_opportunity__c                       float64
of__c                                        float64
temp_max_est_fin__c                          float64
lender_type__c                               float64
lender_marketing_tier__c                     float64
temp_max_primary_est_fin__c                  float64
ss_investors__c                              float64
locations__c                                 float64
temp_max_est_fin_compare__c                  float64
of_opportunities__c                          float64
of_activities_associated__c                  float64
ss_employee_range__c                         float64
most_recent_employee_count_history__c        float64
lead_priority__c                             float64
primary_opportunity_next_steps__c            float64
tier__c                                      float64
lead_score__c                                float64
moved_to_passed_account__c                   float64
primary_est_financial_year__c                float64
primary_est_financial_comments__c            float64
most_recent_engagement__c                    float64
most_recent_project__c                       float64
most_recent_project_amount__c                float64
avg_likely_to_recommend__c                   float64
moved_to_6_indication_submitted__c           float64
sps_sf_addon__city__c                        float64
ss_investors_short__c                        float64
update_flag_inverted__c                      float64
sps_sf_addon__company_description__c         float64
sps_sf_addon__company_key__c                 float64
sps_sf_addon__company_name__c                float64
sps_sf_addon__company_type_name__c           float64
sps_sf_addon__country__c                     float64
sps_sf_addon__firm_flag_indicator__c         float64
sps_sf_addon__firm_note_indicator__c         float64
sps_sf_addon__harmonize_name__c              float64
sps_sf_addon__institution_type__c            float64
sps_sf_addon__is_de_linked__c                float64
sps_sf_addon__note__c                        float64
sps_sf_addon__region__c                      float64
sps_sf_addon__sps_dealcount__c               float64
sps_sf_addon__seen_count__c                  float64
sps_sf_addon__seen_percent__c                float64
sps_sf_addon__shown_count__c                 float64
sps_sf_addon__state__c                       float64
sps_sf_addon__sync_datetime__c               float64
sps_sf_addon__trim_harmonize_name__c         float64
x18charid__c                                 float64
company_review_date__c                       float64
ss_linkedin_url__c                           float64
ss_description__c                            float64
ss_website__c                                    str
ss_company_name__c                               str
ss_year_founded__c                           float64
ss_city__c                                       str
ss_state__c                                      str
ss_phone__c                                      str
ss_employees__c                              float64
ss_postal_code__c                            float64
ss_sourcescrub_link__c                       float64
ss_ownership__c                              float64
ss_most_recent_date_of_investment__c         float64
ss_most_recent_amount_received__c            float64
ss_total_amount_invested__c                  float64
update_flag__c                               float64
opp_id_from_stage__c                         float64
survive_delete__c                            float64
job_openings__c                              float64
aum__c                                       float64
ria_type__c                                  float64
total_accounts__c                            float64
custodian_provider__c                        float64
avg_account_size__c                          float64
rh2__testcurrency__c                         float64
udujobs__c                                   float64
primary_opp_sourcing_lead_user__c            float64
extid__c                                     float64
most_engaged_contact__c                      float64
engagment_level_at_8_scorecard__c            float64
linkedin_url_to_text__c                      float64
sourcing_lead_user_change__c                 float64
influencer_coverage_lead__c                  float64
date_influencer_coverage_assigned__c         float64
recommended_lead_score__c                    float64
model_fit__c                                 float64
sps_sf_addon__text_harmonize_name__c         float64
referral_source_firm_relationship_lead__c    float64
feederfundload__c                            float64
pod__c                                       float64
minimum__c                                   float64
maximum_mm__c                                float64
fund_size_mm__c                              float64
most_recent_investor_s__c                    float64
most_recent_investors__c                     float64
m_1_rls__c                                   float64
m_2_rls__c                                   float64
retail_institutional__c                      float64
accounting_tax_practice__c                   float64
aum_in_millions__c                           float64
tactical_10__c                               float64
products_services__c                         float64
pod_company__c                               float64
leading_investors__c                         float64
participating_investors__c                   float64
status__c                                    float64
most_recent_investor_1__c                    float64
most_recent_investor_2__c                    float64
rollup_mr_lead_inv__c                        float64
most_recent_leading_investors__c             float64
most_recent_participating_investors__c       float64
logo_url__c                                  float64
cold_no_contact__c                           float64
rollup_mr_participating_inv__c               float64
salesloft1__active_account__c                float64
salesloft1__salesloft_domain__c              float64
company_name_for_emails__c                   float64
bofc__bofc_acc_name__c                       float64
primary_opportunity_type__c                  float64
pitchbook_id__c                                  str
pitchbook_link__c                            float64
mandate_geo__c                               float64
transaction_types__c                         float64
fund_vintage__c                              float64
rounds_they_lead_in__c                       float64
rounds_they_invest_in__c                     float64
business_model__c                            float64
data_quality_score__c                        float64
data_quality_description__c                  float64
scale_of_company__c                          float64
revenue_model__c                             float64
relevant_pods__c                             float64
relevant_pods_other__c                       float64
stage_of_investment__c                       float64
scale_of_company_min__c                      float64
scale_of_company_max__c                      float64
fintrx_firm_crd_id__c                        float64
fintrx_url__c                                float64
fintrx_total_aum__c                          float64
fintrx_classification__c                     float64
fintrx_dataset__c                            float64
fintrx_x1_year_aum_growth__c                 float64
fintrx_x3_year_aum_growth__c                 float64
fintrx_x5_year_aum_growth__c                 float64
acquired_merged__c                           float64
keystone_recommended_lead_score__c           float64
rls_delta__c                                 float64
last_logged_activity__c                      float64
acquired_by_merged_with__c                   float64
company_source__c                            float64
source__c                                    float64
estimated_arr__c                             float64

rows: 100

               dtype  nulls  null_pct  distinct  distinct_pct
id               str      0       0.0       100         100.0
name             str      0       0.0       100         100.0
billingcity      str      0       0.0        83          83.0
billingstate     str      0       0.0        35          35.0
billingcountry   str      0       0.0         2           2.0
phone            str      6       6.0        94         100.0
website          str      9       9.0        91         100.0
domain__c        str      4       4.0        96         100.0

In [6]:
cols = [
    "id", "name", "billingcity", "billingstate", "billingcountry",
    "phone", "website", "domain__c",
    "ss_company_name__c", "ss_website__c", "ss_city__c",
    "ss_state__c", "ss_phone__c", "ss_year_founded__c",
]

accounts_sub = accounts[cols].copy()
accounts_sub.head()

,id,name,billingcity,billingstate,billingcountry,phone,website,domain__c,ss_company_name__c,ss_website__c,ss_city__c,ss_state__c,ss_phone__c,ss_year_founded__c
0,00157Q1WAHSCDPHCUN,"Rare Earth Exploration, LLC",Garland,Texas,United States,(469) 480-3141,https://rareearthex.com,rareearthex.com,"Rare Earth Exploration, LLC",https://rareearthex.com,Garland,Texas,+14694803141,2016.0
1,001R7G4RI0GA09H5ZJ,Kenton Grant Consulting,Tulsa,Oklahoma,United States,+19188123774,https://www.kentongrantconsulting.com,kentongrantconsulting.com,Kenton Grant Consulting,https://kentongrantconsulting.com,Tulsa,Oklahoma,+19188123774,2014.0
2,0012ABVJ564CCELZ4K,"GUTHY-RENKER, LLC",El Segundo,California,United States,888-651-6602,https://guthy-renker.com,guthy-renker.com,"Guthy-Renker, LLC",https://guthy-renker.com,El Segundo,California,888-651-6602,1988.0
3,001R0ST0DTW00BXMZZ,SOS TRUCK SERVICE,Ontario,California,United States,(888) 999-9767,NaN,NaN,SOS TRUCK SERVICE,NaN,Ontario,California,+18889999767,1967.0
4,00186JM0HJK76GBGEK,Nutrition Partners Inc.,Airdrie,Alberta,Canada,403-912-0735,https://nutritionpartners.ca,nutritionpartners.ca,"Nutrition Partners, Inc.",https://nutritionpartners.ca,Airdrie,Alberta,+14039120735,2003.0

In [7]:
accounts_sub.dtypes

id                        str
name                      str
billingcity               str
billingstate              str
billingcountry            str
phone                     str
website                   str
domain__c                 str
ss_company_name__c        str
ss_website__c             str
ss_city__c                str
ss_state__c               str
ss_phone__c               str
ss_year_founded__c    float64
dtype: object

In [8]:
accounts_sub["ss_year_founded__c"] = accounts_sub["ss_year_founded__c"].astype("Int64")

In [9]:
accounts_sub = accounts_sub.rename(columns={"domain__c": "domain"})

In [10]:
pd.set_option("display.max_columns", None)   # show all columns

In [11]:
check = accounts_sub.merge(company, on="domain", how="left", indicator=True)

print(check["_merge"].value_counts())
check.head()

_merge
both          62
left_only     38
right_only     0
Name: count, dtype: int64

,id_x,name,billingcity,billingstate,billingcountry,phone,website_x,domain,ss_company_name__c,ss_website__c,ss_city__c,ss_state__c,ss_phone__c,ss_year_founded__c,id_y,normalized_name,informalname,cleaned_informalname,website_y,normalized_phone,city,state,postalcode,country,foundingyear,companytype,parentid,parentcompany,totalamountinvested,nolongerinbusiness,modified_date,_merge
0,00157Q1WAHSCDPHCUN,"Rare Earth Exploration, LLC",Garland,Texas,United States,(469) 480-3141,https://rareearthex.com,rareearthex.com,"Rare Earth Exploration, LLC",https://rareearthex.com,Garland,Texas,+14694803141,2016,840010.0,Rare Earth Exploration,Rare Earth Exploration,rare earth exploration,https://www.rareearthex.com,+14694803141,Garland,Texas,75044,United States,2016,1.0,<NA>,NaN,<NA>,False,2025-04-04,both
1,001R7G4RI0GA09H5ZJ,Kenton Grant Consulting,Tulsa,Oklahoma,United States,+19188123774,https://www.kentongrantconsulting.com,kentongrantconsulting.com,Kenton Grant Consulting,https://kentongrantconsulting.com,Tulsa,Oklahoma,+19188123774,2014,21859623.0,Kenton Grant Consulting,Kenton Grant Consulting,kenton grant consulting,https://www.kentongrantconsulting.com,+19188123774,Tulsa,Oklahoma,74101,United States,2014,1.0,<NA>,NaN,<NA>,False,2026-08-11,both
2,0012ABVJ564CCELZ4K,"GUTHY-RENKER, LLC",El Segundo,California,United States,888-651-6602,https://guthy-renker.com,guthy-renker.com,"Guthy-Renker, LLC",https://guthy-renker.com,El Segundo,California,888-651-6602,1988,1035025.0,Guthy-Renker,Guthy-Renker,guthy-renker,https://www.guthy-renker.com,+18886516602,El Segundo,California,90245,United States,1988,1.0,<NA>,NaN,<NA>,False,2025-09-06,both
3,001R0ST0DTW00BXMZZ,SOS TRUCK SERVICE,Ontario,California,United States,(888) 999-9767,NaN,NaN,SOS TRUCK SERVICE,NaN,Ontario,California,+18889999767,1967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
4,00186JM0HJK76GBGEK,Nutrition Partners Inc.,Airdrie,Alberta,Canada,403-912-0735,https://nutritionpartners.ca,nutritionpartners.ca,"Nutrition Partners, Inc.",https://nutritionpartners.ca,Airdrie,Alberta,+14039120735,2003,708165.0,Nutrition Partners,Nutrition Partners,nutrition partners,https://nutritionpartners.ca,+14039120735,Airdrie,Alberta,T4A 2G8,Canada,2003,1.0,<NA>,NaN,<NA>,False,2025-04-19,both

In [12]:
accounts_sub.loc[accounts_sub["domain"].isna()]

,id,name,billingcity,billingstate,billingcountry,phone,website,domain,ss_company_name__c,ss_website__c,ss_city__c,ss_state__c,ss_phone__c,ss_year_founded__c
3,001R0ST0DTW00BXMZZ,SOS TRUCK SERVICE,Ontario,California,United States,(888) 999-9767,NaN,NaN,SOS TRUCK SERVICE,NaN,Ontario,California,+18889999767,1967
10,001NF6AKQPMKUMYVPY,Dorado Industries,Rancho Palos Verdes,California,United States,310-544-1316,NaN,NaN,Dorado Industries,NaN,Rancho Palos Verdes,California,+13105441316,2006
30,0019JZFX6KJWSK7KEG,Full Canopy Tree Care,Austin,Texas,United States,+15123368733,NaN,NaN,"Full Canopy Tree Care, LLC",NaN,Austin,Texas,(512) 336-8733,2003
31,001XF266CCIFU6FD6Y,"CONCRETE SOFTWARE, INC.",Eden Prairie,Minnesota,United States,+19529425162,NaN,NaN,"Concrete Software, Inc.",https://concretesoftware.com,Eden Prairie,Minnesota,+19529425162,2003

In [39]:
pd.set_option("display.max_rows", 20)
accounts_sub.loc[
    accounts_sub["domain"].astype("string").str.startswith("www.", na=False)
]

,id,name,billingcity,billingstate,billingcountry,phone,website,domain,ss_company_name__c,ss_website__c,ss_city__c,ss_state__c,ss_phone__c,ss_year_founded__c,phone_std,ss_phone_std
14,0018HSSRRXQQM2PLPP,"Burke Estate & Tax Law, LLC",Murfreesboro,Tennessee,United States,+16152171414,https://burketaxlaw.com,www.burketaxlaw.com,"Burke Estate & Tax Law, LLC",https://burketaxlaw.com,Murfreesboro,Tennessee,+16152171414,2020,+16152171414,+16152171414
16,001TINX4KIAPJ2GEJR,Eve and Nico Gifts and Home Decor,Englewood,New Jersey,United States,(212) 280-0999,NaN,www.eveandnico.com,Eve and Nico Gifts and Home Decor,https://eveandnico.com,Englewood,New Jersey,212-280-0999,2014,+12122800999,+12122800999
17,0012WM4F8U7318JZFD,GADSDEN COUNTRY CLUB,Gadsden,Alabama,United States,(256) 546-0451,https://www.thegadsdencountryclub.com,www.thegadsdencountryclub.com,Gadsden Country Club,https://thegadsdencountryclub.com,Gadsden,Alabama,256-546-0451,1919,+12565460451,+12565460451
22,001KGTQ9BBGMQB37P2,Proby's Tax & Accounting Service,Los Angeles,California,United States,+13232909034,https://probystax.com,www.probystax.com,Proby's Tax & Accounting Service,https://probystax.com,Los Angeles,California,323-290-9034,1984,+13232909034,+13232909034
26,0015HVMUTIFCZ9Z8DZ,Sanskar Culture Society,Providence,Rhode Island,United States,(888) 864-9262,https://sanskarusa.org,www.sanskarusa.org,Sanskar Culture Society,https://sanskarusa.org,Foxborough,Massachusetts,888-864-9262,2016,+18888649262,+18888649262
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,001ZQ3ABUUD0VKFBJN,Nixon Peabody Trust Co.,Boston,Massachusetts,United States,+16173451309,NaN,www.nixonpeabodytrustcompany.com,Nixon Peabody Trust Co.,https://nixonpeabodytrustcompany.com,Boston,Massachusetts,+16173451309,2019,+16173451309,+16173451309
92,001EVIAMR8AUBNUUB5,Sylvan Dale Guest Ranch,Loveland,Colorado,United States,970-667-3915,https://sylvandale.com,www.sylvandale.com,Sylvan Dale Guest Ranch,https://sylvandale.com,Loveland,Colorado,+19706673915,1946,+19706673915,+19706673915
94,00148AY13F2LOGQOCH,Encore Labs,Pasadena,California,United States,+16266963086,https://encorelabs.com,www.encorelabs.com,"Encore Labs, LLC",https://encorelabs.com,Pasadena,California,626-696-3086,2017,+16266963086,+16266963086
95,001EH1W9PYM3SWP1CR,"CHAMPLAIN VALLEY ORGANICS, LLC DBA VERMONT PUR...",Shoreham,Vermont,United States,(802) 282-3058,https://www.vermontpurecbd.com,www.vermontpurecbd.com,"Champlain Valley Organics, LLC dba Vermont Pur...",https://vermontpurecbd.com,Shoreham,Vermont,802-282-3058,2017,+18022823058,+18022823058
98,001JM05Z2V7FKXUXET,"Retirement Strategies Group, LLC (RSG)",New Orleans,Louisiana,United States,(504) 712-0005,https://www.rsgweb.com,www.rsgweb.com,"Retirement Strategies Group, LLC (RSG)",https://rsgweb.com,New Orleans,Louisiana,504-712-0005,1999,+15047120005,+15047120005

In [32]:
accounts_sub.loc[
    accounts_sub["domain"].astype("string").str.startswith("https", na=False)
]

Empty DataFrame
Columns: [id, name, billingcity, billingstate, billingcountry, phone, website, domain, ss_company_name__c, ss_website__c, ss_city__c, ss_state__c, ss_phone__c, ss_year_founded__c, phone_std, ss_phone_std]
Index: []

In [13]:
accounts_sub.loc[accounts_sub["website"].isna()]

,id,name,billingcity,billingstate,billingcountry,phone,website,domain,ss_company_name__c,ss_website__c,ss_city__c,ss_state__c,ss_phone__c,ss_year_founded__c
3,001R0ST0DTW00BXMZZ,SOS TRUCK SERVICE,Ontario,California,United States,(888) 999-9767,NaN,NaN,SOS TRUCK SERVICE,NaN,Ontario,California,+18889999767,1967
10,001NF6AKQPMKUMYVPY,Dorado Industries,Rancho Palos Verdes,California,United States,310-544-1316,NaN,NaN,Dorado Industries,NaN,Rancho Palos Verdes,California,+13105441316,2006
16,001TINX4KIAPJ2GEJR,Eve and Nico Gifts and Home Decor,Englewood,New Jersey,United States,(212) 280-0999,NaN,www.eveandnico.com,Eve and Nico Gifts and Home Decor,https://eveandnico.com,Englewood,New Jersey,212-280-0999,2014
30,0019JZFX6KJWSK7KEG,Full Canopy Tree Care,Austin,Texas,United States,+15123368733,NaN,NaN,"Full Canopy Tree Care, LLC",NaN,Austin,Texas,(512) 336-8733,2003
31,001XF266CCIFU6FD6Y,"CONCRETE SOFTWARE, INC.",Eden Prairie,Minnesota,United States,+19529425162,NaN,NaN,"Concrete Software, Inc.",https://concretesoftware.com,Eden Prairie,Minnesota,+19529425162,2003
35,001CRGEWM2YBDOZC2D,"KAUFMAN CHAMBER OF COMMERCE, INC.",Kaufman,Texas,United States,(972) 932-3118,NaN,kaufmanchamber.com,NaN,NaN,NaN,NaN,NaN,<NA>
40,0010Z2EAYJ409GF4NJ,FIKE'S ROOFING & CONSTRUCTION,Shelton,Washington,United States,360-490-0013,NaN,fikesroofing.com,NaN,https://fikesroofing.com,Shelton,Washington,+13604900013,2023
75,001NCDRTMHT2HKU23X,M247,St. Petersburg,Florida,United States,844-284-6247,NaN,www.m247.net,M247,https://m247.net,St. Petersburg,Florida,+18442846247,2018
83,001ZQ3ABUUD0VKFBJN,Nixon Peabody Trust Co.,Boston,Massachusetts,United States,+16173451309,NaN,www.nixonpeabodytrustcompany.com,Nixon Peabody Trust Co.,https://nixonpeabodytrustcompany.com,Boston,Massachusetts,+16173451309,2019

In [44]:
accounts_sub.loc[
    accounts_sub["website"].astype("string").str.startswith("www", na=False)
]

Empty DataFrame
Columns: [id, name, billingcity, billingstate, billingcountry, phone, website, domain, ss_company_name__c, ss_website__c, ss_city__c, ss_state__c, ss_phone__c, ss_year_founded__c, phone_std, ss_phone_std]
Index: []

In [41]:
pd.set_option("display.max_rows", 20)
accounts_sub.loc[
    accounts_sub["website"].astype("string").str.startswith("https", na=False)
]

,id,name,billingcity,billingstate,billingcountry,phone,website,domain,ss_company_name__c,ss_website__c,ss_city__c,ss_state__c,ss_phone__c,ss_year_founded__c,phone_std,ss_phone_std
0,00157Q1WAHSCDPHCUN,"Rare Earth Exploration, LLC",Garland,Texas,United States,(469) 480-3141,https://rareearthex.com,rareearthex.com,"Rare Earth Exploration, LLC",https://rareearthex.com,Garland,Texas,+14694803141,2016,+14694803141,+14694803141
1,001R7G4RI0GA09H5ZJ,Kenton Grant Consulting,Tulsa,Oklahoma,United States,+19188123774,https://www.kentongrantconsulting.com,kentongrantconsulting.com,Kenton Grant Consulting,https://kentongrantconsulting.com,Tulsa,Oklahoma,+19188123774,2014,+19188123774,+19188123774
2,0012ABVJ564CCELZ4K,"GUTHY-RENKER, LLC",El Segundo,California,United States,888-651-6602,https://guthy-renker.com,guthy-renker.com,"Guthy-Renker, LLC",https://guthy-renker.com,El Segundo,California,888-651-6602,1988,+18886516602,+18886516602
4,00186JM0HJK76GBGEK,Nutrition Partners Inc.,Airdrie,Alberta,Canada,403-912-0735,https://nutritionpartners.ca,nutritionpartners.ca,"Nutrition Partners, Inc.",https://nutritionpartners.ca,Airdrie,Alberta,+14039120735,2003,+14039120735,+14039120735
5,001PMACI6O1GBDUEHH,Lucent Path Advisors,Waupun,Wisconsin,United States,(932) 385-6729,https://lucentpathadvisors.com,lucentpathadvisors.com,Lucent Path Advisors,https://lucentpathadvisors.com,Waupun,Wisconsin,(932) 385-6729,2022,+19323856729,+19323856729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,001EH1W9PYM3SWP1CR,"CHAMPLAIN VALLEY ORGANICS, LLC DBA VERMONT PUR...",Shoreham,Vermont,United States,(802) 282-3058,https://www.vermontpurecbd.com,www.vermontpurecbd.com,"Champlain Valley Organics, LLC dba Vermont Pur...",https://vermontpurecbd.com,Shoreham,Vermont,802-282-3058,2017,+18022823058,+18022823058
96,0018EYGPNNHCCFS4GI,"AMS Caregivers, Inc.",Emmaus,Pennsylvania,United States,+16109667033,https://amscaregivers.com,amscaregivers.com,"AMS Caregivers, Inc.",https://amscaregivers.com,Emmaus,Pennsylvania,+16109667033,1997,+16109667033,+16109667033
97,0012L1ITBHJAITJ6WG,Bateman Laboratories Inc.,Toronto,Ontario,Canada,(942) 573-8417,https://batemanlabs.ca,batemanlabs.ca,Bateman Laboratories Inc.,https://batemanlabs.ca,Toronto,Ontario,(942) 573-8417,1993,+19425738417,+19425738417
98,001JM05Z2V7FKXUXET,"Retirement Strategies Group, LLC (RSG)",New Orleans,Louisiana,United States,(504) 712-0005,https://www.rsgweb.com,www.rsgweb.com,"Retirement Strategies Group, LLC (RSG)",https://rsgweb.com,New Orleans,Louisiana,504-712-0005,1999,+15047120005,+15047120005
99,0015CWGW9UHCPQWM2B,"Apex Tool Company, Inc",Columbus,Indiana,United States,812-579-5478,https://apexinds.com,apexinds.com,"Apex Tool Company, Inc",https://apexinds.com,Columbus,Indiana,812-579-5478,1975,+18125795478,+18125795478

In [43]:
pd.set_option("display.max_rows", 20)
accounts_sub.loc[
    accounts_sub["ss_website__c"].astype("string").str.startswith("www.", na=False)
]

Empty DataFrame
Columns: [id, name, billingcity, billingstate, billingcountry, phone, website, domain, ss_company_name__c, ss_website__c, ss_city__c, ss_state__c, ss_phone__c, ss_year_founded__c, phone_std, ss_phone_std]
Index: []

In [42]:
pd.set_option("display.max_rows", 20)
accounts_sub.loc[
    accounts_sub["ss_website__c"].astype("string").str.startswith("https", na=False)
]

,id,name,billingcity,billingstate,billingcountry,phone,website,domain,ss_company_name__c,ss_website__c,ss_city__c,ss_state__c,ss_phone__c,ss_year_founded__c,phone_std,ss_phone_std
0,00157Q1WAHSCDPHCUN,"Rare Earth Exploration, LLC",Garland,Texas,United States,(469) 480-3141,https://rareearthex.com,rareearthex.com,"Rare Earth Exploration, LLC",https://rareearthex.com,Garland,Texas,+14694803141,2016,+14694803141,+14694803141
1,001R7G4RI0GA09H5ZJ,Kenton Grant Consulting,Tulsa,Oklahoma,United States,+19188123774,https://www.kentongrantconsulting.com,kentongrantconsulting.com,Kenton Grant Consulting,https://kentongrantconsulting.com,Tulsa,Oklahoma,+19188123774,2014,+19188123774,+19188123774
2,0012ABVJ564CCELZ4K,"GUTHY-RENKER, LLC",El Segundo,California,United States,888-651-6602,https://guthy-renker.com,guthy-renker.com,"Guthy-Renker, LLC",https://guthy-renker.com,El Segundo,California,888-651-6602,1988,+18886516602,+18886516602
4,00186JM0HJK76GBGEK,Nutrition Partners Inc.,Airdrie,Alberta,Canada,403-912-0735,https://nutritionpartners.ca,nutritionpartners.ca,"Nutrition Partners, Inc.",https://nutritionpartners.ca,Airdrie,Alberta,+14039120735,2003,+14039120735,+14039120735
5,001PMACI6O1GBDUEHH,Lucent Path Advisors,Waupun,Wisconsin,United States,(932) 385-6729,https://lucentpathadvisors.com,lucentpathadvisors.com,Lucent Path Advisors,https://lucentpathadvisors.com,Waupun,Wisconsin,(932) 385-6729,2022,+19323856729,+19323856729
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,001EH1W9PYM3SWP1CR,"CHAMPLAIN VALLEY ORGANICS, LLC DBA VERMONT PUR...",Shoreham,Vermont,United States,(802) 282-3058,https://www.vermontpurecbd.com,www.vermontpurecbd.com,"Champlain Valley Organics, LLC dba Vermont Pur...",https://vermontpurecbd.com,Shoreham,Vermont,802-282-3058,2017,+18022823058,+18022823058
96,0018EYGPNNHCCFS4GI,"AMS Caregivers, Inc.",Emmaus,Pennsylvania,United States,+16109667033,https://amscaregivers.com,amscaregivers.com,"AMS Caregivers, Inc.",https://amscaregivers.com,Emmaus,Pennsylvania,+16109667033,1997,+16109667033,+16109667033
97,0012L1ITBHJAITJ6WG,Bateman Laboratories Inc.,Toronto,Ontario,Canada,(942) 573-8417,https://batemanlabs.ca,batemanlabs.ca,Bateman Laboratories Inc.,https://batemanlabs.ca,Toronto,Ontario,(942) 573-8417,1993,+19425738417,+19425738417
98,001JM05Z2V7FKXUXET,"Retirement Strategies Group, LLC (RSG)",New Orleans,Louisiana,United States,(504) 712-0005,https://www.rsgweb.com,www.rsgweb.com,"Retirement Strategies Group, LLC (RSG)",https://rsgweb.com,New Orleans,Louisiana,504-712-0005,1999,+15047120005,+15047120005
99,0015CWGW9UHCPQWM2B,"Apex Tool Company, Inc",Columbus,Indiana,United States,812-579-5478,https://apexinds.com,apexinds.com,"Apex Tool Company, Inc",https://apexinds.com,Columbus,Indiana,812-579-5478,1975,+18125795478,+18125795478

In [14]:
accounts_sub[["phone", "ss_phone__c"]].isna().sum()

phone           6
ss_phone__c    21
dtype: int64

In [15]:
digits_phone = accounts_sub["phone"].astype("string").str.replace(r"\D", "", regex=True)
digits_phone.str.len().value_counts(dropna=False).sort_index()

phone
10      68
11      26
<NA>     6
Name: count, dtype: Int64

In [27]:
check = accounts_sub.merge(
    company,
    left_on="phone",
    right_on="normalized_phone",
    how="left",
    indicator=True,
)
print(check["_merge"].value_counts())
check.head()

_merge
left_only     74
both          26
right_only     0
Name: count, dtype: int64

,id_x,name,billingcity,billingstate,billingcountry,phone,website_x,domain_x,ss_company_name__c,ss_website__c,ss_city__c,ss_state__c,ss_phone__c,ss_year_founded__c,phone_std,ss_phone_std,id_y,normalized_name,informalname,cleaned_informalname,website_y,domain_y,normalized_phone,city,state,postalcode,country,foundingyear,companytype,parentid,parentcompany,totalamountinvested,nolongerinbusiness,modified_date,_merge
0,00157Q1WAHSCDPHCUN,"Rare Earth Exploration, LLC",Garland,Texas,United States,(469) 480-3141,https://rareearthex.com,rareearthex.com,"Rare Earth Exploration, LLC",https://rareearthex.com,Garland,Texas,+14694803141,2016,+14694803141,+14694803141,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
1,001R7G4RI0GA09H5ZJ,Kenton Grant Consulting,Tulsa,Oklahoma,United States,+19188123774,https://www.kentongrantconsulting.com,kentongrantconsulting.com,Kenton Grant Consulting,https://kentongrantconsulting.com,Tulsa,Oklahoma,+19188123774,2014,+19188123774,+19188123774,21859623.0,Kenton Grant Consulting,Kenton Grant Consulting,kenton grant consulting,https://www.kentongrantconsulting.com,kentongrantconsulting.com,+19188123774,Tulsa,Oklahoma,74101,United States,2014,1.0,<NA>,NaN,<NA>,False,2026-08-11,both
2,0012ABVJ564CCELZ4K,"GUTHY-RENKER, LLC",El Segundo,California,United States,888-651-6602,https://guthy-renker.com,guthy-renker.com,"Guthy-Renker, LLC",https://guthy-renker.com,El Segundo,California,888-651-6602,1988,+18886516602,+18886516602,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
3,001R0ST0DTW00BXMZZ,SOS TRUCK SERVICE,Ontario,California,United States,(888) 999-9767,NaN,NaN,SOS TRUCK SERVICE,NaN,Ontario,California,+18889999767,1967,+18889999767,+18889999767,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
4,00186JM0HJK76GBGEK,Nutrition Partners Inc.,Airdrie,Alberta,Canada,403-912-0735,https://nutritionpartners.ca,nutritionpartners.ca,"Nutrition Partners, Inc.",https://nutritionpartners.ca,Airdrie,Alberta,+14039120735,2003,+14039120735,+14039120735,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only

In [16]:
accounts_sub["phone"].dropna().astype(str).str.replace(r"\d", "D", regex=True).value_counts()

phone
(DDD) DDD-DDDD    48
+DDDDDDDDDDD      26
DDD-DDD-DDDD      20
Name: count, dtype: int64

In [17]:
digits = accounts_sub["phone"].astype("string").str.replace(r"\D", "", regex=True)

na_countries = {"united states", "canada"}
is_na = accounts_sub["billingcountry"].astype("string").str.strip().str.lower().isin(na_countries)

m10 = (digits.str.len() == 10) & is_na
m11 = (digits.str.len() == 11) & digits.str.startswith("1")

accounts_sub["phone_std"] = accounts_sub["phone"]
accounts_sub.loc[m10, "phone_std"] = "+1" + digits[m10]
accounts_sub.loc[m11, "phone_std"] = "+" + digits[m11]

print(m10.sum(), "+1 added;", m11.sum(), "already had the 1")

68 +1 added; 26 already had the 1

In [18]:
accounts_sub["phone_std"].dropna().astype(str).str.replace(r"\d", "D", regex=True).value_counts()

phone_std
+DDDDDDDDDDD    94
Name: count, dtype: int64

In [28]:
check = accounts_sub.merge(
    company,
    left_on="phone_std",
    right_on="normalized_phone",
    how="left",
    indicator=True,
)
print(check["_merge"].value_counts())
check.head()

_merge
both          83
left_only     17
right_only     0
Name: count, dtype: int64

,id_x,name,billingcity,billingstate,billingcountry,phone,website_x,domain_x,ss_company_name__c,ss_website__c,ss_city__c,ss_state__c,ss_phone__c,ss_year_founded__c,phone_std,ss_phone_std,id_y,normalized_name,informalname,cleaned_informalname,website_y,domain_y,normalized_phone,city,state,postalcode,country,foundingyear,companytype,parentid,parentcompany,totalamountinvested,nolongerinbusiness,modified_date,_merge
0,00157Q1WAHSCDPHCUN,"Rare Earth Exploration, LLC",Garland,Texas,United States,(469) 480-3141,https://rareearthex.com,rareearthex.com,"Rare Earth Exploration, LLC",https://rareearthex.com,Garland,Texas,+14694803141,2016,+14694803141,+14694803141,840010.0,Rare Earth Exploration,Rare Earth Exploration,rare earth exploration,https://www.rareearthex.com,rareearthex.com,+14694803141,Garland,Texas,75044,United States,2016,1.0,<NA>,NaN,<NA>,False,2025-04-04,both
1,001R7G4RI0GA09H5ZJ,Kenton Grant Consulting,Tulsa,Oklahoma,United States,+19188123774,https://www.kentongrantconsulting.com,kentongrantconsulting.com,Kenton Grant Consulting,https://kentongrantconsulting.com,Tulsa,Oklahoma,+19188123774,2014,+19188123774,+19188123774,21859623.0,Kenton Grant Consulting,Kenton Grant Consulting,kenton grant consulting,https://www.kentongrantconsulting.com,kentongrantconsulting.com,+19188123774,Tulsa,Oklahoma,74101,United States,2014,1.0,<NA>,NaN,<NA>,False,2026-08-11,both
2,0012ABVJ564CCELZ4K,"GUTHY-RENKER, LLC",El Segundo,California,United States,888-651-6602,https://guthy-renker.com,guthy-renker.com,"Guthy-Renker, LLC",https://guthy-renker.com,El Segundo,California,888-651-6602,1988,+18886516602,+18886516602,1035025.0,Guthy-Renker,Guthy-Renker,guthy-renker,https://www.guthy-renker.com,guthy-renker.com,+18886516602,El Segundo,California,90245,United States,1988,1.0,<NA>,NaN,<NA>,False,2025-09-06,both
3,001R0ST0DTW00BXMZZ,SOS TRUCK SERVICE,Ontario,California,United States,(888) 999-9767,NaN,NaN,SOS TRUCK SERVICE,NaN,Ontario,California,+18889999767,1967,+18889999767,+18889999767,17382874.0,SOS TRUCK SERVICE,SOS TRUCK SERVICE,sos truck service,http://www.sostruckservice.com,sostruckservice.com,+18889999767,Ontario,California,91761,United States,1967,1.0,<NA>,NaN,<NA>,False,2026-02-27,both
4,00186JM0HJK76GBGEK,Nutrition Partners Inc.,Airdrie,Alberta,Canada,403-912-0735,https://nutritionpartners.ca,nutritionpartners.ca,"Nutrition Partners, Inc.",https://nutritionpartners.ca,Airdrie,Alberta,+14039120735,2003,+14039120735,+14039120735,708165.0,Nutrition Partners,Nutrition Partners,nutrition partners,https://nutritionpartners.ca,nutritionpartners.ca,+14039120735,Airdrie,Alberta,T4A 2G8,Canada,2003,1.0,<NA>,NaN,<NA>,False,2025-04-19,both

In [19]:
check = accounts_sub.merge(
    company,
    left_on="ss_phone__c",
    right_on="normalized_phone",
    how="left",
    indicator=True,
)
print(check["_merge"].value_counts())
check.head()

_merge
left_only     58
both          42
right_only     0
Name: count, dtype: int64

,id_x,name,billingcity,billingstate,billingcountry,phone,website_x,domain_x,ss_company_name__c,ss_website__c,ss_city__c,ss_state__c,ss_phone__c,ss_year_founded__c,phone_std,id_y,normalized_name,informalname,cleaned_informalname,website_y,domain_y,normalized_phone,city,state,postalcode,country,foundingyear,companytype,parentid,parentcompany,totalamountinvested,nolongerinbusiness,modified_date,_merge
0,00157Q1WAHSCDPHCUN,"Rare Earth Exploration, LLC",Garland,Texas,United States,(469) 480-3141,https://rareearthex.com,rareearthex.com,"Rare Earth Exploration, LLC",https://rareearthex.com,Garland,Texas,+14694803141,2016,+14694803141,840010.0,Rare Earth Exploration,Rare Earth Exploration,rare earth exploration,https://www.rareearthex.com,rareearthex.com,+14694803141,Garland,Texas,75044,United States,2016,1.0,<NA>,NaN,<NA>,False,2025-04-04,both
1,001R7G4RI0GA09H5ZJ,Kenton Grant Consulting,Tulsa,Oklahoma,United States,+19188123774,https://www.kentongrantconsulting.com,kentongrantconsulting.com,Kenton Grant Consulting,https://kentongrantconsulting.com,Tulsa,Oklahoma,+19188123774,2014,+19188123774,21859623.0,Kenton Grant Consulting,Kenton Grant Consulting,kenton grant consulting,https://www.kentongrantconsulting.com,kentongrantconsulting.com,+19188123774,Tulsa,Oklahoma,74101,United States,2014,1.0,<NA>,NaN,<NA>,False,2026-08-11,both
2,0012ABVJ564CCELZ4K,"GUTHY-RENKER, LLC",El Segundo,California,United States,888-651-6602,https://guthy-renker.com,guthy-renker.com,"Guthy-Renker, LLC",https://guthy-renker.com,El Segundo,California,888-651-6602,1988,+18886516602,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
3,001R0ST0DTW00BXMZZ,SOS TRUCK SERVICE,Ontario,California,United States,(888) 999-9767,NaN,NaN,SOS TRUCK SERVICE,NaN,Ontario,California,+18889999767,1967,+18889999767,17382874.0,SOS TRUCK SERVICE,SOS TRUCK SERVICE,sos truck service,http://www.sostruckservice.com,sostruckservice.com,+18889999767,Ontario,California,91761,United States,1967,1.0,<NA>,NaN,<NA>,False,2026-02-27,both
4,00186JM0HJK76GBGEK,Nutrition Partners Inc.,Airdrie,Alberta,Canada,403-912-0735,https://nutritionpartners.ca,nutritionpartners.ca,"Nutrition Partners, Inc.",https://nutritionpartners.ca,Airdrie,Alberta,+14039120735,2003,+14039120735,708165.0,Nutrition Partners,Nutrition Partners,nutrition partners,https://nutritionpartners.ca,nutritionpartners.ca,+14039120735,Airdrie,Alberta,T4A 2G8,Canada,2003,1.0,<NA>,NaN,<NA>,False,2025-04-19,both

In [20]:
digits = accounts_sub["ss_phone__c"].astype("string").str.replace(r"\D", "", regex=True)
digits.str.len().value_counts(dropna=False).sort_index()

ss_phone__c
10      36
11      43
<NA>    21
Name: count, dtype: Int64

In [21]:
# distinct values with record counts (includes nulls)
accounts_sub["billingcountry"].value_counts(dropna=False)

billingcountry
United States    90
Canada           10
Name: count, dtype: int64

In [22]:
accounts["ss_phone__c"].dropna().astype(str).str.replace(r"\d", "D", regex=True).value_counts()

ss_phone__c
+DDDDDDDDDDD      43
DDD-DDD-DDDD      24
(DDD) DDD-DDDD    11
DDD.DDD.DDDD       1
Name: count, dtype: int64

In [23]:
digits = accounts_sub["ss_phone__c"].astype("string").str.replace(r"\D", "", regex=True)

na_countries = {"united states", "canada"}
is_na = accounts_sub["billingcountry"].astype("string").str.strip().str.lower().isin(na_countries)

m10 = (digits.str.len() == 10) & is_na
m11 = (digits.str.len() == 11) & digits.str.startswith("1")

accounts_sub["ss_phone_std"] = accounts_sub["ss_phone__c"]
accounts_sub.loc[m10, "ss_phone_std"] = "+1" + digits[m10]
accounts_sub.loc[m11, "ss_phone_std"] = "+" + digits[m11]

print(m10.sum(), "+1 added;", m11.sum(), "already had the 1")

36 +1 added; 43 already had the 1

In [24]:
accounts_sub["ss_phone_std"].dropna().astype(str).str.replace(r"\d", "D", regex=True).value_counts()

ss_phone_std
+DDDDDDDDDDD    79
Name: count, dtype: int64

In [25]:
check = accounts_sub.merge(
    company,
    left_on="ss_phone_std",       # not ss_phone__c
    right_on="normalized_phone",
    how="left",
    indicator=True,
)
print(check["_merge"].value_counts())
check.head()

_merge
both          68
left_only     32
right_only     0
Name: count, dtype: int64

,id_x,name,billingcity,billingstate,billingcountry,phone,website_x,domain_x,ss_company_name__c,ss_website__c,ss_city__c,ss_state__c,ss_phone__c,ss_year_founded__c,phone_std,ss_phone_std,id_y,normalized_name,informalname,cleaned_informalname,website_y,domain_y,normalized_phone,city,state,postalcode,country,foundingyear,companytype,parentid,parentcompany,totalamountinvested,nolongerinbusiness,modified_date,_merge
0,00157Q1WAHSCDPHCUN,"Rare Earth Exploration, LLC",Garland,Texas,United States,(469) 480-3141,https://rareearthex.com,rareearthex.com,"Rare Earth Exploration, LLC",https://rareearthex.com,Garland,Texas,+14694803141,2016,+14694803141,+14694803141,840010.0,Rare Earth Exploration,Rare Earth Exploration,rare earth exploration,https://www.rareearthex.com,rareearthex.com,+14694803141,Garland,Texas,75044,United States,2016,1.0,<NA>,NaN,<NA>,False,2025-04-04,both
1,001R7G4RI0GA09H5ZJ,Kenton Grant Consulting,Tulsa,Oklahoma,United States,+19188123774,https://www.kentongrantconsulting.com,kentongrantconsulting.com,Kenton Grant Consulting,https://kentongrantconsulting.com,Tulsa,Oklahoma,+19188123774,2014,+19188123774,+19188123774,21859623.0,Kenton Grant Consulting,Kenton Grant Consulting,kenton grant consulting,https://www.kentongrantconsulting.com,kentongrantconsulting.com,+19188123774,Tulsa,Oklahoma,74101,United States,2014,1.0,<NA>,NaN,<NA>,False,2026-08-11,both
2,0012ABVJ564CCELZ4K,"GUTHY-RENKER, LLC",El Segundo,California,United States,888-651-6602,https://guthy-renker.com,guthy-renker.com,"Guthy-Renker, LLC",https://guthy-renker.com,El Segundo,California,888-651-6602,1988,+18886516602,+18886516602,1035025.0,Guthy-Renker,Guthy-Renker,guthy-renker,https://www.guthy-renker.com,guthy-renker.com,+18886516602,El Segundo,California,90245,United States,1988,1.0,<NA>,NaN,<NA>,False,2025-09-06,both
3,001R0ST0DTW00BXMZZ,SOS TRUCK SERVICE,Ontario,California,United States,(888) 999-9767,NaN,NaN,SOS TRUCK SERVICE,NaN,Ontario,California,+18889999767,1967,+18889999767,+18889999767,17382874.0,SOS TRUCK SERVICE,SOS TRUCK SERVICE,sos truck service,http://www.sostruckservice.com,sostruckservice.com,+18889999767,Ontario,California,91761,United States,1967,1.0,<NA>,NaN,<NA>,False,2026-02-27,both
4,00186JM0HJK76GBGEK,Nutrition Partners Inc.,Airdrie,Alberta,Canada,403-912-0735,https://nutritionpartners.ca,nutritionpartners.ca,"Nutrition Partners, Inc.",https://nutritionpartners.ca,Airdrie,Alberta,+14039120735,2003,+14039120735,+14039120735,708165.0,Nutrition Partners,Nutrition Partners,nutrition partners,https://nutritionpartners.ca,nutritionpartners.ca,+14039120735,Airdrie,Alberta,T4A 2G8,Canada,2003,1.0,<NA>,NaN,<NA>,False,2025-04-19,both

In [26]:
check[check["_merge"] == "left_only"]

,id_x,name,billingcity,billingstate,billingcountry,phone,website_x,domain_x,ss_company_name__c,ss_website__c,ss_city__c,ss_state__c,ss_phone__c,ss_year_founded__c,phone_std,ss_phone_std,id_y,normalized_name,informalname,cleaned_informalname,website_y,domain_y,normalized_phone,city,state,postalcode,country,foundingyear,companytype,parentid,parentcompany,totalamountinvested,nolongerinbusiness,modified_date,_merge
5,001PMACI6O1GBDUEHH,Lucent Path Advisors,Waupun,Wisconsin,United States,(932) 385-6729,https://lucentpathadvisors.com,lucentpathadvisors.com,Lucent Path Advisors,https://lucentpathadvisors.com,Waupun,Wisconsin,(932) 385-6729,2022,+19323856729,+19323856729,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
7,001VOQ4CT939RX77RI,Happy Period,Palmdale,California,United States,NaN,https://hashtaghappyperiod.org,hashtaghappyperiod.org,Happy Period,https://hashtaghappyperiod.org,Palmdale,California,NaN,2015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
9,0017RUE8OQQ4W74OJE,Quarrystone Capital Partners,Cary,North Carolina,United States,(925) 354-2292,https://quarrystonecapital.com,quarrystonecapital.com,Quarrystone Capital Partners,https://quarrystonecapital.com,Cary,North Carolina,(925) 354-2292,1992,+19253542292,+19253542292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
11,001DJZDNBJ0DDLZ2UH,PrecisionChem LLC,Waupun,Wisconsin,United States,+19203242007,https://precisionchemllc.com,precisionchemllc.com,NaN,NaN,NaN,NaN,NaN,<NA>,+19203242007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
12,001UAY5GCQ8NKM7WG3,Helix Intelligence Group,San Francisco,California,United States,NaN,https://www.centrum-ai.com,centrum-ai.com,Centrum-AI Inc.,https://centrum-ai.com,San Francisco,California,NaN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
13,001LWUOXI9XQPDCGZD,OpenText Enterprise Apps Fund (OTEAF),Toronto,Ontario,Canada,416-306-3020,https://firstascenntures.com,firstascenntures.com,NaN,NaN,NaN,NaN,NaN,<NA>,+14163063020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
15,001OTNZEKJCBHGKWJB,Professional Communicators LLC,Littleton,Colorado,United States,(866) 785-8255,https://procommunicators.com,procommunicators.com,NaN,NaN,NaN,NaN,NaN,<NA>,+18667858255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
18,0014B0PZCYC3EDQMEV,"Overhead Door of Nova Scotia, Ltd",Dartmouth,Nova Scotia,Canada,(902) 455-5469,https://ohdns.ca,ohdns.ca,NaN,NaN,NaN,NaN,NaN,<NA>,+19024555469,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
27,001RT5NK4RITSFVA5P,Palmwood Dental Partners,Rancho Palos Verdes,California,United States,(542) 661-7381,https://palmwooddental.com,palmwooddental.com,Palmwood Dental Partners,https://palmwooddental.com,Rancho Palos Verdes,California,(542) 661-7381,2005,+15426617381,+15426617381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
29,001BJTAYFLOUMGE9X6,Thirteen Barrels Brewing Co.,Lafayette,Colorado,United States,(303) 997-4164,https://odd13brewing.com,odd13brewing.com,NaN,NaN,NaN,NaN,NaN,<NA>,+13039974164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
33,0013LCUYX1H0JQYGXW,Windrow Agricultural Systems,Montesano,Washington,United States,(982) 830-8453,https://windrowag.com,windrowag.com,Windrow Agricultural Systems,https://windrowag.com,Montesano,Washington,(982) 830-8453,1989,+19828308453,+19828308453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
34,001SNSDBK9EW2D7Y2W,"HAEGER, INC.",Grand Rapids,Michigan,United States,(209) 848-4000,https://haeger.com,www.haeger.com,NaN,NaN,NaN,NaN,NaN,<NA>,+12098484000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
35,001CRGEWM2YBDOZC2D,"KAUFMAN CHAMBER OF COMMERCE, INC.",Kaufman,Texas,United States,(972) 932-3118,NaN,kaufmanchamber.com,NaN,NaN,NaN,NaN,NaN,<NA>,+19729323118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
36,001IHD86N9LQXJLK7B,Brightwell Analytics,Ontario,California,United States,(705) 212-2881,https://brightwellanalytics.io,brightwellanalytics.io,Brightwell Analytics,https://brightwellanalytics.io,Ontario,California,(705) 212-2881,2012,+17052122881,+17052122881,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
37,001QH7DX297GQ8ZXQY,Celerity Risk,Atlanta,Georgia,United States,NaN,https://celerityrisk.com,celerityrisk.com,Celerity Risk,https://celerityrisk.com,Atlanta,Georgia,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
39,001UBGAEZWDOY0YOBQ,Corvid Logistics Group,Fort Atkinson,Wisconsin,United States,(958) 980-9188,https://corvidlogistics.com,corvidlogistics.com,Corvid Logistics Group,https://corvidlogistics.com,Fort Atkinson,Wisconsin,(958) 980-9188,2012,+19589809188,+19589809188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
47,001P10OOLH31UQG0PZ,"ABSOLUTE MOBILE DRUG TESTING, LLC",Coeur d'Alene,Idaho,United States,509-747-8855,https://adtlab.com,www.adtlab.com,NaN,NaN,NaN,NaN,NaN,<NA>,+15097478855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
49,001NA3Z2ZTKEJTTQ9V,ABC Sand & Rock,Phoenix,Arizona,United States,(602) 272-1792,https://www.abcsandrock.com,abcsandrock.com,NaN,NaN,NaN,NaN,NaN,<NA>,+16022721792,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
56,001XVJCNQCNAU0XLTE,"IC Mechanical, Inc.",Tampa,Florida,United States,+18138184889,https://icmech.com,www.icmech.com,NaN,NaN,NaN,NaN,NaN,<NA>,+18138184889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
62,001Q5EPYO0TZ5BPFLK,Elite Pain and Health PC,Oklahoma City,Oklahoma,United States,(800) 781-1220,https://epainhealth.com,epainhealth.com,NaN,NaN,NaN,NaN,NaN,<NA>,+18007811220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
67,001XCAN3THI1FMHWKX,HOLSTEIN PLAZA,North Hudson,Wisconsin,United States,(240) 329-0169,https://www.holsteinplaza.com,holsteinplaza.com,NaN,NaN,NaN,NaN,NaN,<NA>,+12403290169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
68,001PYYYO2SAUQR1KCS,Smoke Bud,Waterloo,Iowa,United States,NaN,https://smokebudapp.com,smokebudapp.com,Smoke Bud,https://smokebudapp.com,Waterloo,Iowa,NaN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
69,0010IVGXV479NS1V1Q,"Fadstir, Inc.",Los Angeles,California,United States,+18327153017,https://fadstir.com,fadstir.com,NaN,NaN,NaN,NaN,NaN,<NA>,+18327153017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
72,001S9V0RZ1U80YJYY0,Argent Field Services,Burlington,Vermont,United States,(526) 591-7374,https://argentfieldservices.com,argentfieldservices.com,Argent Field Services,https://argentfieldservices.com,Burlington,Vermont,(526) 591-7374,2020,+15265917374,+15265917374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
74,001Z8KF9TM5N7F2H9H,"Oconee Rental, Inc",Watkinsville,Georgia,United States,(706) 769-9390,https://oconeerental.com,oconeerental.com,NaN,NaN,NaN,NaN,NaN,<NA>,+17067699390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
76,001MHFCDZ9U29U3A44,Sable Ridge Vineyards,Oakville,Ontario,Canada,(936) 798-4821,https://sableridgevineyards.com,sableridgevineyards.com,Sable Ridge Vineyards,https://sableridgevineyards.com,Oakville,Ontario,(936) 798-4821,2011,+19367984821,+19367984821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
84,001E2VUO4HXJVODL29,"Crestline Transportation, Inc.",Shady Cove,Oregon,United States,541-878-3467,https://crestlinetrans.com,crestlinetrans.com,NaN,NaN,NaN,NaN,NaN,<NA>,+15418783467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
87,001GXSPJETVX6PW9ZV,"Plastic Components, Inc.",Germantown,Wisconsin,United States,(877) 253-1496,https://plasticcomponents.com,plasticcomponents.com,"Plastic Components, Inc.",https://plasticcomponents.com,Germantown,Wisconsin,+18772531496,1989,+18772531496,+18772531496,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
88,001W5EWNOERLAQRECM,Dorado Industrial Group,Phoenix,Arizona,United States,(749) 391-2601,https://doradoindustrial.com,doradoindustrial.com,Dorado Industrial Group,https://doradoindustrial.com,Phoenix,Arizona,(749) 391-2601,2014,+17493912601,+17493912601,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
89,001M0LDGWC0AAT9ATZ,Dream Vision Basketball,San Juan Capistrano,California,United States,NaN,https://www.dreamvisionbasketball.com,dreamvisionbasketball.com,NaN,https://dreamvisionbasketball.com,San Juan Capistrano,California,NaN,2006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
91,0017QTUACOJS106XDI,"Blue Egg Advisory, LLC",Boulder,Colorado,United States,NaN,https://blueeggadvisory.com,blueeggadvisory.com,"Blue Egg Advisory, LLC",https://blueeggadvisory.com,Boulder,Colorado,NaN,2014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only
97,0012L1ITBHJAITJ6WG,Bateman Laboratories Inc.,Toronto,Ontario,Canada,(942) 573-8417,https://batemanlabs.ca,batemanlabs.ca,Bateman Laboratories Inc.,https://batemanlabs.ca,Toronto,Ontario,(942) 573-8417,1993,+19425738417,+19425738417,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,<NA>,NaN,<NA>,NaN,NaT,left_only

- 4 recs dont have domains in accounts
- 9 recs dont have websites
- standardizing ss_phone__c improves match from 42 to 68 (+26), 21/32 still null (11 genuinely have no match)
- standardizing phone improves match from 26 to 83 (+57), 6/17 still null (11 genuinely have no match)
- ss_year_founded__c convert to int

In [29]:
con.close()